// Responsibility: Assemble parsed Easel operations into one MASSO/RapidChange G-code program.
// This first version preserves the cutting body from each file while replacing file-level endings
// and inserting RapidChange calls between operations.

import { toolChangeBlock } from "./rapidchange.js";

export function buildJob(operations, settings) {
  if (!operations.length) throw new Error("Add at least one .nc file.");

  const lines = [];
  lines.push("(Easel -> MASSO RapidChange ATC Job Composer)");
  lines.push("(Generated by JavaScript Job Composer)");
  lines.push("G17");
  lines.push("G20");
  lines.push("G80");
  lines.push("G90");
  lines.push("G54");

  let previousTool = null;

  operations.forEach((operation, index) => {
    const tool = Number(operation.tool);
    if (!Number.isInteger(tool) || tool < 1 || tool > 8) {
      throw new Error(`Operation ${index + 1} has invalid RapidChange tool ${operation.tool}.`);
    }

    lines.push("");
    lines.push(`(===== START OPERATION ${index + 1}: ${operation.fileName} =====)`);
    lines.push(`(Tool ${tool}${operation.description ? `: ${operation.description}` : ""})`);

    if (previousTool !== tool) {
      lines.push(toolChangeBlock(tool, settings, previousTool));
    } else {
      lines.push("(Same tool as previous operation - no tool change)");
    }

    lines.push(operation.body);
    lines.push(`(===== END OPERATION ${index + 1}: ${operation.fileName} =====)`);

    previousTool = tool;
  });

  lines.push("");
  lines.push("(===== JOB END =====)");
  lines.push(`G00 Z${Number(settings.parkZ).toFixed(3)}`);
  lines.push("M5");
  lines.push("M9");
  lines.push("M30");

  return lines.join("\n") + "\n";
}
